---
- hosts: nginx_servers
  become: yes
  vars:
    reactjs_host_ip: #input your local IP
    reactjs_host_port: #input EXPOSE port
    project_path: "/etc/nginx/sites-enabled"
    root_group: "root"
  
  tasks:
  - name: Update APT package cache
    apt:
      update_cache: yes
  
  - name: Install Nginx
    apt:
      name: nginx
      state: present
    ignore_errors: yes
  
  - name: Delete Nginx default
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/sites-enabled/default
    notify: NGINX_reload

  - name: Add Nginx config
    template:
      src: nginx.conf.j2
      dest: "/etc/nginx/sites-enabled/nginx.conf"
      owner: root
      mode: '0644'
    notify: NGINX_reload

  pre_tasks:
    - name: Ensure that the default nginx symlink is absent
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      async: 200
      poll: 0

    - name: validate nginx configuration
      command: nginx -t -c /etc/nginx/nginx.conf
      changed_when: false
      ignore_errors: yes

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      when: nginx_service_state == "started"
