---
- hosts: reactjs_servers
  
  vars:
    project_path: /var/www
    repository: https://gitlab.skillbox.ru/indichenko_boris/9_skillbox-deploy-blue-green.git
    packages:
      - yarn
      - npm
      - nodejs
      - git

  tasks:
    - name: Yarn | GPG
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: Yarn | Ensure Debian sources list file exists
      file:
        path: /etc/apt/sources.list.d/yarn.list
        owner: root
        mode: 0644
        state: touch

    - name: Yarn | Ensure Debian package is in sources list
      lineinfile:
        dest: /etc/apt/sources.list.d/yarn.list
        regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
        line: 'deb http://dl.yarnpkg.com/debian/ stable main'
        state: present

    - name: Yarn | Update APT cache
      apt:
        update_cache: yes

    - name: Install the packages YARN, NPM, NodeJS, Nginx
      apt:
        pkg: "{{ item }}"
      loop: "{{ packages }}"
      #tags: install_packages

    - name: Set some variable
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

    - name: Create project path
      file: 
        dest={{ project_path }} 
        mode=0755 
        recurse=yes 
        state=directory

    - name: Create Release folder
      file: 
        dest={{ release_path }} 
        mode=0755 
        recurse=yes 
        state=directory

    - name: Clone the repository
      git:
        dest: "{{ release_path }}"
        repo: "{{ repository }}"

    - name: Add IP address of instance to main site
      replace:
        path: "{{ release_path }}/src/App.js"
        regexp: Test of revert
        replace: "{{ ansible_default_ipv4.address }}"
        backup: 'yes'

    - npm:
        name: pm2
        global: 'yes'

    - name: Install packages based on package.json.
      yarn:
        path: "{{ release_path }}"

    - name: Start application
      command: pm2 --name ReactJS start npm -- start
      args:
        chdir: "{{ release_path }}"
      environment:
        PORT: 80
      tags: start_yarn

